version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - ./data:/data
      - ./mods:/mods
      - ./plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      OPS: "bill_ferny"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      VERSION: "1.19.2"
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true
