version: "3"

services:
  mc:
    image: itzg/minecraft-server
    volumes:
      - ./data:/data
      - ./mods:/mods
      - ./plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: true
      OPS: "bill_ferny"
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      VERSION: "1.19.2"
      SNOOPER_ENABLED: false
      MEMORY: "4G"
      EXTRA_ARGS: "--nogui"
      JVM_XX_OPTS: "-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
    tty: true
    stdin_open: true
    restart: unless-stopped
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
      PAUSE_IF_NO_PLAYERS: true
      PRE_BACKUP_SCRIPT: /pre-backup.sh
      POST_BACKUP_SCRIPT_FILE: /post-backup.sh
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
      - ./post-backup.sh:/post-backup.sh:ro
      - ./pre-backup.sh:/pre-backup.sh:ro
    network_mode: "service:mc"
volumes:
  mc:
    external: true
  backups:
    external: true
